// <auto-generated />
using DAy_7.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAy_7.DAL.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAy_7.DAL.Entities.CongTy", b =>
                {
                    b.Property<string>("MaCty")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("SLNV")
                        .HasColumnType("int");

                    b.Property<string>("TenCty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCty");

                    b.ToTable("CongTys");
                });

            modelBuilder.Entity("DAy_7.DAL.Entities.NhanVien", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<bool>("AmTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaCty")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("SoLanXN")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaCty");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("DAy_7.DAL.Entities.NhanVien", b =>
                {
                    b.HasOne("DAy_7.DAL.Entities.CongTy", "CongTy")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaCty")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongTy");
                });

            modelBuilder.Entity("DAy_7.DAL.Entities.CongTy", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
